#!/usr/bin/env bash
# This script installs and configures nginx
sudo apt-get install -y nginx
if ! pgrep nginx > /dev/null ; then
	/usr/sbin/nginx
fi
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.html
cat > /etc/nginx/sites-available/default <<EOF
server {
listen 80 default_server;
listen [::]:80 default_server;

root /var/www/html;
index index.html;

error_page 404 /404.html;

location /404.html {
	internal;
}

location / {
	try_files \$uri \$uri/ =404;
	add_header Content-Type "text/html";
	return 200 'Hello World!';
}

location /redirect_me {
	rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}
}
EOF

if pgrep nginx > /dev/null; then
	kill -HUP "$(pgrep nginx)"
else
	/usr/sbin/nginx
fi
