#!/usr/bin/env bash
# This script adds a custom header to the http response
sudo apt-get update
sudo apt-get install nginx -y
sudo systemctl start nginx

cat > /etc/nginx/conf.d/custom_http_response_header <<EOF
add_header X-Served-By $hostname;
EOF

sudo nginx -t
sudo systemctl reload nginx
