#!/usr/bin/env bash
# This script adds a custom header to the http response
sudo apt-get update
sudo apt-get install nginx -y
sudo systemctl start nginx

sudo bash -c "cat > /etc/nginx/conf.d/custom_http_response_header.conf" <<EOL
add_header X-Served-By \$hostname;
EOL

sudo nginx -t
sudo systemctl reload nginx
