#!/usr/bin/env bash
# This script displays "Best School" 10 times using while loop
i=0

while (( i<=12 ))
do
	j=1

	echo "Hour: $i"
	while (( j <=59 ))
	do
		echo $j
		(( j++ ))
	done
	(( i++ ))
done
