#!/usr/bin/env bash
# This configures nginx to run as nginx user

# Configure Nginx to run as the nginx user
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Update Nginx config file to listen on port 8080
sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default

sudo service nginx restart
