#!/usr/bin/env bash
# This configures nginx to run as nginx user

# Configure Nginx to run as the nginx user
sudo sed -i '1\i user nginx;' /etc/nginx/nginx.conf

# Update Nginx config file to listen on port 8080
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-enabled/default

sudo service nginx restart
